package com.example.Recipes.models;

import java.util.ArrayList;

public enum InstructionType {

    FLOURLESS_CHOC_CAKE("8 large eggs, cold: 1 lb. dark, semisweet or bittersweet chocolate, coarsely chopped: 16 Tbsp. (2 sticks) unsalted butter, cut into 16 pieces: optional toppings: powdered sugar and/or berries + Adjust an oven rack to the lower-middle position and heat the oven to 325°F.: Line the bottom of an 8-inch springform pan with parchment paper or waxed paper and grease the sides of the pan. (Be sure to grease the sides really well!) Wrap the outside of the pan with 2 sheets of heavy-duty aluminum foil and set it in a large roasting pan, or any pan that’s larger than the springform.: Bring a kettle or pot of water to boil.: In a stand mixer using the whisk attachment, beat the eggs at high speed until the volume doubles. This usually takes about 5 minutes.: Meanwhile, melt the chocolate and butter together. You can either do this in a double boiler on the stove (by placing the chocolate and butter in a large heatproof bowl, set over a pan of almost-simmering water, and stirring until melted and smooth). Or you can do this in the microwave (by heating the chocolate and butter in a microwave-safe bowl in 30-second intervals, stirring in between, until the chocolate and butter are melted and smooth).: Then fold about a third of the beaten eggs into the chocolate mixture using a large rubber spatula until only a few streaks of egg are visible.: Fold in half of the remaining egg foam, and then the last half of the foam, until the mixture is totally homogenous.: Scrape the batter into the prepared springform pan and smooth the surface with a rubber spatula. Place the roasting pan on the oven rack and VERY carefully pour in enough boiling water to come about halfway up the sides of the springform pan.: Bake until the cake has risen slightly, the edges are just beginning to set, a thin-glazed crust (like a brownie) has formed on the surface, and an instant-read thermometer inserted halfway into the center reads 140° F, 22-25 minutes.: Remove the springform pan from the water bath and set on a wire rack; cool to room temperature. Cover and refrigerate until cool. (The cake can be refrigerated for up to 4 days.): About 30 minutes prior to serving, carefully remove the sides of the springform pan, invert the cake onto a sheet of waxed paper, peel off the parchment paper, and reinvert the cake onto a serving platter.: If desired, lightly dust the cake with powdered sugar and top with berries. To slice, use a sharp, thin-bladed knife, dipping the knife into a pitcher of hot water and wiping the blade before each cut."),
    NUTELLA_BROWNIE("1 1/4 cup Nutella: 2 large eggs: 1/2 cup all purpose flour + Preheat oven to 350°F.: Grease a 9 inch x 9 inch metal baking pan.: Add all ingredients into a large bowl and mix until batter is smooth.: Pour into baking pan and smooth top with spatula.: Bake for about 15 minutes until toothpick inserted comes out clean. Be careful not to bake too long otherwise brownies will dry out.: Let brownies cool and set before cutting and serving."),
    PEANUT_BUTTER_COOKIES("200g peanut butter (crunchy or smooth is fine): 175g golden caster sugar: ¼ tsp fine table salt: 1 large egg + Heat oven to 180C/160C fan/gas 4 and line 2 large baking trays with baking parchment.: Measure the peanut butter and sugar into a bowl. Add ¼ tsp fine table salt and mix well with a wooden spoon. Add the egg and mix again until the mixture forms a dough.: Break off cherry tomato sized chunks of dough and place, well spaced apart, on the trays. Press the cookies down with the back of a fork to squash them a little. The cookies can now be frozen for 2 months, cook from frozen adding an extra min or 2 to the cooking time.: Bake for 12 mins, until golden around the edges and paler in the centre. Cool on the trays for 10 mins, then transfer to a wire rack and cool completely. Store in a cookie jar for up to 3 days."),
    BASIC_MUFFINS("2 medium eggs: 125ml vegetable oil: 250ml semi-skimmed milk: 250g golden caster sugar: 400g self-raising flour (or same quantity plain flour and 3 tsp baking powder): 1 tsp salt: 100g chocolate chips or dried fruit such as sultanas or dried cherries (optional) + Heat oven to 200C/180C fan/gas 6.: Line 2 muffin trays with paper muffin cases.: In a large bowl beat 2 medium eggs lightly with a handheld electric mixer for 1 min.: Add 125ml vegetable oil and 250ml semi-skimmed milk and beat until just combined then add 250g golden caster sugar and whisk until you have a smooth batter.: Sift in 400g self-raising flour and 1 tsp salt (or 400g plain flour and 3 tsp baking powder if using) then mix until just smooth. Be careful not to over-mix the batter as this will make the muffins tough.: Stir in 100g chocolate chips or dried fruit if using.: Fill muffin cases two-thirds full and bake for 20-25 mins, until risen, firm to the touch and a skewer inserted in the middle comes out clean. If the trays will not fit on 1 shelf, swap the shelves around after 15 mins of cooking.: Leave the muffins in the tin to cool for a few mins and transfer to a wire rack to cool completely."),
    VICTORIA_SANDWICH("200g caster sugar: 200g softened butter: 4 eggs (beaten): 200g self-raising flour: 1 tsp baking powder: 2 tbsp milk: For the filling: 100g butter (softened): 140g icing sugar (sifted): 1 drop vanilla extract (optional): half a 340g jar good-quality strawberry jam (we used Tiptree Little Scarlet): icing sugar, to decorate + Heat oven to 190C/fan 170C/gas 5.: Butter two 20cm sandwich tins and line with non-stick baking paper.: In a large bowl, beat 200g caster sugar, 200g softened butter, 4 beaten eggs, 200g self-raising flour, 1 tsp baking powder and 2 tbsp milk together until you have a smooth, soft batter.: Divide the mixture between the tins, smooth the surface with a spatula or the back of a spoon.: Bake for about 20 mins until golden and the cake springs back when pressed.: Turn onto a cooling rack and leave to cool completely.: To make the filling, beat the 100g softened butter until smooth and creamy, then gradually beat in 140g sifted icing sugar and a drop of vanilla extract (if you’re using it).: Spread the buttercream over the bottom of one of the sponges.: Top it with 170g strawberry jam and sandwich the second sponge on top.: Dust with a little icing sugar before serving.: Keep in an airtight container and eat within 2 days."),
    BANANA_LOAF("140g butter, softened, plus extra for the tin: 140g caster sugar: 2 large eggs, beaten: 140g self-raising flour: 1 tsp baking powder: 2 very ripe bananas, mashed: 50g icing sugar: handful dried banana chips, for decoration + Heat oven to 180C/160C fan/gas 4.: Butter a 2lb loaf tin and line the base and sides with baking parchment.: Cream 140g softened butter and 140g caster sugar until light and fluffy, then slowly add 2 beaten large eggs with a little of the 140g flour.: Fold in the remaining flour, 1 tsp baking powder and 2 mashed bananas.: Pour into the tin and bake for about 30 mins until a skewer comes out clean.: Cool in the tin for 10 mins, then remove to a wire rack.: Mix 50g icing sugar with 2-3 tsp water to make a runny icing.: Drizzle the icing across the top of the cake and decorate with a handful of banana chips.");


    private final String value;

    InstructionType(String value) {
        this.value = value;
    }

    public String getValue() {
        return this.value;
    }

}
